{{- $_ := set . "Version" ( splitList "/" (env "GITHUB_REF" ) | last ) }}
{{- $_ := set . "BaseURL" ( printf "%s" .Version | lower | replace "+" "-plus-" | replace "." "-dot-"  ) }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .BaseURL }}
  annotations:
    "werf.io/set-replicas-only-on-creation": "true"
  labels:
    service: {{ .Chart.Name }}-{{ .BaseURL }}
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      service: {{ .Chart.Name }}-{{ .BaseURL }}
  template:
    metadata:
      labels:
        service: {{ .Chart.Name }}-{{ .BaseURL }}
    spec:
      imagePullSecrets:
        - name: registrysecret
      containers:
        - name: web
          command: ["nginx", "-g", "daemon off;"]
{{ tuple ( printf "site-%s" .BaseURL  ) . | include "werf_container_image" | indent 10 }}
{{- include "resources" . | indent 8 }}
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx", "-s", "quit"]
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
{{ tuple ( printf "site-%s" .BaseURL  ) . | include "werf_container_env" | indent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .BaseURL }}
spec:
  clusterIP: None
  selector:
    service: {{ .Chart.Name }}-{{ .BaseURL }}
  ports:
  - name: http
    port: 80
    protocol: TCP
