{{- $_ := set . "Version" ( splitList "/" (env "GITHUB_REF" ) | last ) }}
{{- $_ := set . "BaseURL" ( printf "%s" .Version | lower | replace "+" "-plus-" | replace "." "-dot-"  ) }}
{{- $host := .Values.global.ci_url }}

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-{{ .BaseURL }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      ssi on;
{{- if eq .Values.global.env "production" }}
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
{{- else }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
{{- end }}
spec:
  tls:
  - hosts:
      - {{ $host }}
      - ru.{{ $host }}
{{- if eq .Values.global.env "production" }}
      - www.{{ $host }}
{{- end }}
    secretName: tls-{{ $host }}
  rules:
  - host: {{ $host }}
    http:
      paths:
{{- if eq .Version "master" }}
      - path: /
{{- else }}
      - path: /{{ .Version }}
{{- end }}
        backend:
          serviceName: {{ .Chart.Name }}-{{ .BaseURL }}
          servicePort: 80
  - host: ru.{{ $host }}
    http:
      paths:
{{- if eq .Version "master" }}
      - path: /
{{- else }}
      - path: /{{ .Version }}
{{- end }}
        backend:
          serviceName: {{ .Chart.Name }}-{{ .BaseURL }}
          servicePort: 80
---
{{- if eq .Version "master" }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Chart.Name }}-cert
spec:
  secretName: tls-{{ $host }}
  issuerRef:
    kind: ClusterIssuer
{{- if eq .Values.global.env "production" }}
    name: letsencrypt
{{- else }}
    name: letsencrypt-staging
{{- end }}
  commonName: {{ $host }}
  dnsNames:
  - {{ $host }}
  - ru.{{ $host }}
{{- if eq .Values.global.env "production" }}
  - www.{{ $host }}
{{- end }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - {{ $host }}
      - ru.{{ $host }}
{{- if eq .Values.global.env "production" }}
      - www.{{ $host }}
{{- end }}
{{- end }}
