en:
  common:
    image:
      signature: "signature: %{signature}"
      info:
        created_at: "date: %{value}"
        size: "size: %{value} MB"
        difference: "difference: %{value} MB"
      commands: "commands:"
      instructions: "instructions:"
    container:
      launched_command: "Launched command: '%{command}'"
    process:
      artifact_copy: "copying artifact '%{name}'"
      artifact_building: "building artifact '%{name}'"
      git_artifact_clone: "cloning remote git_artifact '%{name}'"
      git_artifact_fetch: "fetching remote git_artifact '%{name}'"
      berks_vendor: 'vendoring cookbooks'
      chef_cookbooks_stage_berks_vendor: 'vendoring cookbooks for chef cookbooks stage'
      waiting_resouce_lock: "waiting for locked resource '%{name}'"
      gitartifact_container_loading: 'loading dappdeps/gitartifact container'
      base_container_loading: 'loading dappdeps/base container'
      chefdk_container_loading: 'loading dappdeps/chefdk container'
      system_shellout_container_loading: 'loading system shellout container'
      image_pull: "pulling image '%{name}'"
      image_push: "pushing image '%{name}'"
    status:
      process:
        pushing: '[PUSHING]'
        pulling: '[PULLING]'
        building: '[BUILDING]'
        default: '[RUNNING]'
        tagging: '[TAGGING]'
      success:
        default: '[OK]'
      failed:
        not_pulled: '[NOT PULLED]'
        default: '[FAILED]'
    state:
      using_cache: '[USING CACHE]'
      not_present: '[NOT PRESENT]'
      build: '[BUILD]'
      empty: '[EMPTY]'
      push: '[PUSH]'
      pull: '[PULL]'
      tag: '[TAG]'
    warning:
      excess_builder_instruction: "WARNING: Excessive use of the 'builder' instruction. Builder type will be automatically determined by the first use of any builder."
      excess_name_instruction: "WARNING: Excessive use of the 'name' instruction. Given name corresponds to default name."
      another_image_already_tagged: 'WARNING: image with other id already exist.'
      tag_ignored: "WARNING: tag '%{tag}' ignored."
      dimg_not_found_in_registry: "WARNING: Dimg not found in registry."
    group:
      install_group: 'Install group'
      setup_group: 'Setup group'
    stage:
      from: 'From'
      import_artifact: 'Import Artifact'
      before_install: 'Before install'
      before_install_artifact: 'Before install artifact'
      g_a_archive_dependencies: 'Git artifacts dependencies'
      g_a_archive: 'Git artifacts: create archive'
      install_group:
        g_a_pre_install_patch_dependencies: 'Git artifacts dependencies'
        g_a_pre_install_patch: 'Git artifacts: apply patches (before install)'
        install: 'Install'
        g_a_post_install_patch_dependencies: 'Git artifacts dependencies'
        g_a_post_install_patch: 'Git artifacts: apply patches (after install)'
      after_install_artifact: 'After install artifact'
      before_setup: 'Before setup'
      before_setup_artifact: 'Before setup artifact'
      setup_group:
        g_a_pre_setup_patch_dependencies: 'Git artifacts dependencies'
        g_a_pre_setup_patch: 'Git artifacts: apply patches (before setup)'
        setup: 'Setup'
        chef_cookbooks: 'Сhef сookbooks'
        g_a_post_setup_patch_dependencies: 'Git artifacts dependencies'
        g_a_post_setup_patch: 'Git artifacts: apply patches (after setup)'
      after_setup_artifact: 'After setup artifact'
      g_a_latest_patch: 'Git artifacts: latest patch'
      docker_instructions: 'Docker instructions'
      g_a_artifact_patch: 'Git artifacts: artifact patch'
      build_artifact: 'Build artifact'
